name: Visual Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  run-visual-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install deps
        run: |
          cd playwright-tests-v4
          npm install
          npx playwright install
    
      - name: Set up cache
        id: cache
        uses: actions/cache@v4
        with:
            key: cache/${{github.repository}}/${{github.ref}}
            restore-keys: cache/${{github.repository}}/refs/heads/master
            path: playwright-tests-v4/test-results/**

      - name: Initialize snapshots
        if: ${{steps.cache.outputs.cache-hit != 'true'}}
        run: cd playwright-tests-v4 && npx playwright test --update-snapshots

      - name: Test
        run: cd playwright-tests-v4 && npx playwright test
    
      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-tests-v4/playwright-report/
          retention-days: 30
